config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :content, presence: true
  validates :rating, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.where(restaurant_id: @restaurant.id)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])

    @review.restaurant = @restaurant

    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def update
    if @review.update(review_params)
      redirect_to restaurant_path(@review)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path
  end

  private

  def review_params
    params.require(:review).permit(:restaurant_id, :content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar-wagon">
      <!-- Logo -->
      <%= link_to restaurants_path, class: "navbar-wagon-brand" do %>
        <%= image_tag "logo.png", height: 50 %>
      <% end %>

      <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">

        <!-- Links -->
        <%= link_to "Host", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Trips", "#", class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Messages", "#", class: "navbar-wagon-item navbar-wagon-link" %>

        <!-- Avatar with dropdown menu -->
        <div class="navbar-wagon-item">
          <div class="dropdown">
            <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
            <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
                <% end %>
              </li>
              <li>
                <%= link_to "#" do %>
                  <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Dropdown list appearing on mobile only -->
      <div class="navbar-wagon-item hidden-md hidden-lg">
        <div class="dropdown">
          <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><a href="#">Some mobile link</a></li>
            <li><a href="#">Other one</a></li>
            <li><a href="#">Other one</a></li>
          </ul>
        </div>
      </div>
    </div>


    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: %w(chinese italian japanese french belgian) %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Edit a restaurant</h1>
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>List of all the restaurant</h1>
  <br>
    <ul>
      <% @restaurants.each do |restaurant| %>
        <li>
          <%= link_to restaurant.name, restaurant_path(restaurant) %>
        </li>
      <% end %>
    </ul>
    <br>
    <%= link_to "+ Add a new restaurant", new_restaurant_path,
      class: 'btn btn-primary'
    %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>Create a new restaurant</h1>
  <%= render 'form', restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
  <hr>
  <p><%= @restaurant.address %></p>
  <p><%= @restaurant.phone_number %></p>
  <p><%= @restaurant.category %></p>
  <div class= "row">
    <div class= "col-xs-4">
      <div class="box">
        <%= link_to "Edit the restaurant", edit_restaurant_path(@restaurant),
            class: "btn btn-primary" %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="box">
        <%= link_to "Return to the list", restaurants_path,
          class: 'btn btn-primary'
        %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="box">
        <%= link_to "Create a review", new_restaurant_review_path(@restaurant, @review),
          class: 'btn btn-success'
        %>
      </div>
    </div>
  </div>
  <br>
  <div>
    <h2>This is the restaurant's reviews</h2>
    <ul>
      <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.rating %>
        <%= review.content %>

      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([@restaurant, @review]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: %w(0 1 2 3 4 5) %>
  <%= f.submit %>
<% end %>

app/views/reviews/new.html.erb
<div class="container">
  <h1>Here you can create your Review</h1>
  <%= render 'form', review: @review, restaurant: @restaurant %>
</div>